import { Component, Input, ElementRef, OnChanges, NgZone } from '@angular/core';
import { ICONS } from '../../../lucide-icons';
import type { IconNode } from 'lucide';

/**
 * Dockyard icon wrapper for Lucide icons.
 * Usage: <dy-icon name="box" [size]="16"></dy-icon>
 *
 * Icons are bundled (tree-shaken — see src/app/lucide-icons.ts, regenerated by
 * tools/gen-lucide-subset.mjs) and each glyph is rendered directly into THIS
 * host element. There is no runtime CDN dependency and no global document
 * re-scan, so an icon-dense page paints in O(icons), not O(icons²).
 *
 * Optional inputs mirror the design-system Icon primitive:
 *   [strokeWidth] — line weight (default 1.5)
 *   [color]       — explicit color; when unset, inherits currentColor
 */
const SVG_NS = 'http://www.w3.org/2000/svg';
const FALLBACK = ICONS['box'];

@Component({
  selector: 'dy-icon',
  standalone: true,
  template: '',
})
export class IconComponent implements OnChanges {
  @Input() name = '';
  @Input() size = 16;
  @Input() strokeWidth = 1.5;
  @Input() color = '';

  constructor(private host: ElementRef<HTMLElement>, private zone: NgZone) {}

  // The host element is available from construction, so a single ngOnChanges
  // paints on first render (no separate AfterViewInit pass = no double-paint).
  ngOnChanges(): void { this.paint(); }

  private paint(): void {
    this.zone.runOutsideAngular(() => {
      const el = this.host.nativeElement;
      el.style.display = 'inline-flex';
      el.style.alignItems = 'center';
      el.style.justifyContent = 'center';
      el.style.flex = 'none';
      el.style.width = `${this.size}px`;
      el.style.height = `${this.size}px`;
      el.style.color = this.color || '';

      let node = ICONS[this.name];
      if (!node) {
        if (this.name) console.warn(`[dy-icon] unknown icon "${this.name}" — using fallback`);
        node = FALLBACK;
      }
      el.replaceChildren(this.buildSvg(node));
    });
  }

  private buildSvg(node: IconNode): SVGElement {
    const svg = document.createElementNS(SVG_NS, 'svg');
    svg.setAttribute('xmlns', SVG_NS);
    svg.setAttribute('width', String(this.size));
    svg.setAttribute('height', String(this.size));
    svg.setAttribute('viewBox', '0 0 24 24');
    svg.setAttribute('fill', 'none');
    svg.setAttribute('stroke', 'currentColor');
    svg.setAttribute('stroke-width', String(this.strokeWidth));
    svg.setAttribute('stroke-linecap', 'round');
    svg.setAttribute('stroke-linejoin', 'round');
    this.appendChildren(svg, node);
    return svg;
  }

  // lucide IconNodes are [tag, attrs, children?] tuples (children are rare but
  // possible), so render recursively to stay robust.
  private appendChildren(parent: Element, node: IconNode): void {
    for (const entry of node) {
      const [tag, attrs, children] = entry as [string, Record<string, string | number>, IconNode?];
      const child = document.createElementNS(SVG_NS, tag);
      if (attrs) {
        for (const [k, v] of Object.entries(attrs)) child.setAttribute(k, String(v));
      }
      if (children) this.appendChildren(child, children);
      parent.appendChild(child);
    }
  }
}
